name : Lint

on :
    pull_request :
        branches :
            - dev
            - master

jobs :
    lint:
        runs-on : ubuntu-latest
        name : check lint
        steps :
            - uses : actions/checkout@v3
            - run : npm install
            - run : npm run lint